apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rlrk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rorai-tenant/devfile-sample/devfile-sample-rlrk@sha256:1424cf939100abd81eecfc38699e7d941fd061e4b911734547829ed456cd7b7d
        name: my-nodejs
        resources: {}
status: {}
